import { escapeHTML, formatCurrency, getCurrencySymbol } from '../utils.js';

// Extraído de js/ui.js — centraliza todos los selectores del DOM
export const elements = {
    // Vistas principales
    authContainer: document.getElementById('auth-container'),
    sidebar: document.getElementById('sidebar'),
    mainContent: document.getElementById('main-content'),
    sidebarOverlay: document.getElementById('sidebar-overlay'),
    sidebarOpenBtn: document.getElementById('sidebar-open-btn'),
    sidebarCloseBtn: document.getElementById('sidebar-close-btn'),
    sidebarToggleDesktopBtn: document.getElementById('sidebar-toggle-desktop'),

    // Formularios de autenticación
    loginView: document.getElementById('login-view'),
    registerView: document.getElementById('register-view'),
    loginForm: document.getElementById('login-form'),
    registerForm: document.getElementById('register-form'),
    showRegisterViewBtn: document.getElementById('show-register-view'),
    showLoginViewBtn: document.getElementById('show-login-view'),
    authError: document.getElementById('auth-error'),
    logoutBtn: document.getElementById('logout-btn'),

    navLinks: document.querySelectorAll('.nav-link'),
    pages: document.querySelectorAll('.page-content'),
    transactionForm: document.getElementById('transaction-form'),
    transactionsTableBody: document.getElementById('transactions-table-body'),
    transferForm: document.getElementById('transfer-form'),
    proformaForm: document.getElementById('proforma-form'),
    addAccountForm: document.getElementById('add-account-form'),
    updateBalanceForm: document.getElementById('update-balance-form'),
    reportForm: document.getElementById('report-form'),
    reportDisplayArea: document.getElementById('report-display-area'),
    addIncomeCategoryForm: document.getElementById('add-income-category-form'),
    addExpenseCategoryForm: document.getElementById('add-expense-category-form'),
    addOperationTypeForm: document.getElementById('add-operation-type-form'),
    addTaxIdTypeForm: document.getElementById('add-tax-id-type-form'),
    settingsAccountsList: document.getElementById('settings-accounts-list'),
    incomeCategoriesList: document.getElementById('income-categories-list'),
    expenseCategoriesList: document.getElementById('expense-categories-list'),
    operationTypesList: document.getElementById('operation-types-list'),
    taxIdTypesList: document.getElementById('tax-id-types-list'),
    proformasTableBody: document.getElementById('proformas-table-body'),
    aeatSettingsCard: document.getElementById('aeat-settings-card'),
    aeatToggleContainer: document.getElementById('aeat-toggle-container'),
    aeatConfigForm: document.getElementById('aeat-config-form'),
    nuevaFacturaForm: document.getElementById('nueva-factura-form'),
    facturaItemsContainer: document.getElementById('factura-items-container'),
    facturaAddItemBtn: document.getElementById('factura-add-item-btn'),
    facturaApiResponse: document.getElementById('factura-api-response'),
    facturaOperationType: document.getElementById('factura-operation-type'),
    facturaSelectCliente: document.getElementById('factura-select-cliente'),
    facturasTableBody: document.getElementById('facturas-table-body'),
    defaultFiltersContainer: document.getElementById('default-filters-container'),
    sociedadesFiltersContainer: document.getElementById('sociedades-filters-container'),
    fiscalParamsForm: document.getElementById('fiscal-params-form'),
    invoiceViewerModal: document.getElementById('invoice-viewer-modal'),
    invoiceContentArea: document.getElementById('invoice-content-area'),
    closeInvoiceViewerBtn: document.getElementById('close-invoice-viewer-btn'),
    printInvoiceBtn: document.getElementById('print-invoice-btn'),
    pdfInvoiceBtn: document.getElementById('pdf-invoice-btn'),
    addClientForm: document.getElementById('add-client-form'),
    clientsTableBody: document.getElementById('clients-table-body'),
    investmentsTableBody: document.getElementById('investments-table-body'),
    paymentDetailsModal: document.getElementById('payment-details-modal'),
    paymentDetailsForm: document.getElementById('payment-details-form'),
    paymentDetailsCancelBtn: document.getElementById('payment-details-cancel-btn'),
    transactionIvaContainer: document.getElementById('transaction-iva-container'),
    ivaMonthInput: document.getElementById('iva-month'),
    ivaGenerateReportBtn: document.getElementById('iva-generate-report-btn'),
    ivaReportDisplay: document.getElementById('iva-report-display'),
    loadingOverlay: document.getElementById('loading-overlay'),
    addInvestmentForm: document.getElementById('add-investment-form'),
    addInvestmentAssetForm: document.getElementById('add-investment-asset-form'),
    investmentAssetsList: document.getElementById('investment-assets-list'),
    connectionStatus: document.getElementById('connection-status'),
    statusIcon: document.getElementById('status-icon'),
    statusText: document.getElementById('status-text'),
    newAccountLogoSelect: document.getElementById('new-account-logo-select'),

    // Elementos de gestión de usuarios y permisos (Modal)
    userManagementCard: document.getElementById('user-management-card'),
    usersList: document.getElementById('users-list'),
    permissionsModal: document.getElementById('permissions-modal'),
    permissionsModalEmail: document.getElementById('permissions-modal-email'),
    permissionsList: document.getElementById('permissions-list'),
    permissionsModalSaveBtn: document.getElementById('permissions-modal-save-btn'),
    permissionsModalCancelBtn: document.getElementById('permissions-modal-cancel-btn'),
};
